SELECT *
from EMPLOYEES;

select DEPARTMENT_NAME
from DEPARTMENTS;

select FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES;


select FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
where SALARY > 9000;

--TASK 4
select FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
where SALARY between 9000 and 15000
order by SALARY;

--TASK_5
select FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
where SALARY > 5000
  AND FIRST_NAME = 'Peter'
order by SALARY desc;

--Task6
SELECT COUNTRY_ID, COUNTRY_NAME,REGION_ID
from COUNTRIES
where REGION_ID in (2, 4)
order by REGION_ID desc, COUNTRY_NAME;

--task7
SELECT FIRST_NAME||' '|| LAST_NAME as Full_name, SALARY*12 as annual_salary, JOB_ID
from EMPLOYEES
where JOB_ID
like 'S%';

--task8
select COUNTRY_ID, COUNTRY_NAME
from COUNTRIES
where COUNTRY_NAME LIKE '%a';

---task_9
SELECT COUNTRY_ID,COUNTRY_NAME FROM COUNTRIES
WHERE COUNTRY_NAME like '__i%a';

--task10
