select *
from employees;

--display all first_name and related department_name
SELECT FIRST_NAME, DEPARTMENT_NAME, D.DEPARTMENT_ID
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--ORDER THE LIST BASED ON FIRST_NAME ASC
SELECT FIRST_NAME, DEPARTMENT_NAME, D.DEPARTMENT_ID
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY FIRST_NAME;

--DISPLAY ALL FIRST_NAME AND DEPARTMENT_NAME INCLUDING THE EMPLOYEE WITH OUT DEPARTMENT
SELECT FIRST_NAME, DEPARTMENT_NAME, D.DEPARTMENT_ID
FROM EMPLOYEES E
         LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY FIRST_NAME;

select FIRST_NAME, DEPARTMENT_NAME, D.DEPARTMENT_ID
FROM DEPARTMENTS D
         RIGHT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

--DISPLAY ALL FIRST NAME AND DEPARTMENT NAME INCLUDING THE DEPARTMENT WITHOUT EMPLOYEE

SELECT FIRST_NAME, DEPARTMENT_NAME, D.DEPARTMENT_ID
FROM EMPLOYEES E
         RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT DEPARTMENT_NAME, COUNT(*)
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

--DISPLAY ALL FIRST_NAME AND DEPARTMENT NAME INCLUDING THE DEPARTMENT
-- WITHOUT EMPLOYEES AND ALSO EMPLOYEES WITHOUT THE DEPARTMENT
SELECT FIRST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES E
         full JOIN DEPARTMENTS D ON E.EMPLOYEE_ID = D.DEPARTMENT_ID;

--display all cities and related country name

SELECT CITY, COUNTRY_NAME, C.COUNTRY_ID
FROM LOCATIONS L
         JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID;

--display all cities and related country name including with countries without city

SELECT CITY, COUNTRY_NAME, C.COUNTRY_ID
FROM LOCATIONS L
         RIGHT JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID;
--DISPLAY ALL DEPARTMENT NAME AND RELATED STREET ADDRESS

SELECT *
FROM DEPARTMENTS;
SELECT *
FROM LOCATIONS;
SELECT DEPARTMENT_NAME, STREET_ADDRESS, D.LOCATION_ID
FROM LOCATIONS L
         JOIN DEPARTMENTS D
              ON L.LOCATION_ID = D.LOCATION_ID;

SELECT DEPARTMENT_NAME, STREET_ADDRESS, D.LOCATION_ID, L.LOCATION_ID
FROM LOCATIONS L
         LEFT JOIN DEPARTMENTS D
                   ON L.LOCATION_ID = D.LOCATION_ID;

--DISPLAY ALL FIRST_NAME, LAST_NAME, DEPARTMENT NAME , CITY FOR ALL EMPLOYEES
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY
from EMPLOYEES E
         join DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID
         join LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID;

--DISPLAY ALL FIRST_NAME, LAST_NAME, DEPARTMENT NAME , CITY, COUNTRY_NAME FOR ALL EMPLOYEES

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY, COUNTRY_NAME, REGION_NAME
from EMPLOYEES E
         join DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID
         join LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID
         join COUNTRIES C2 on L.COUNTRY_ID = C2.COUNTRY_ID
         JOIN REGIONS R on C2.REGION_ID = R.REGION_ID;

--HOW MANY EMPLOYEES WORKING FOR EACH COUNTRY_NAME?
SELECT COUNTRY_NAME, COUNT(*)
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
    JOIN LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID
    JOIN COUNTRIES C2 on L.COUNTRY_ID = C2.COUNTRY_ID
group by COUNTRY_NAME
HAVING COUNT(*)>10;

--left join with where
select * from CUSTOMER C LEFT JOIN ADDRESS A on C.ADDRESS_ID = A.ADDRESS_ID
WHERE A.ADDRESS_ID IS NULL ;

--full outer join with where
select * from CUSTOMER C full JOIN ADDRESS A on C.ADDRESS_ID = A.ADDRESS_ID
WHERE A.ADDRESS_ID IS NULL or C.ADDRESS_ID is null;

select FIRST_NAME from EMPLOYEES
where LENGTH(FIRST_NAME)=6;
