SELECT *
FROM EMPLOYEES;

select FIRST_NAME, LAST_NAME
from EMPLOYEES

where EMPLOYEE_ID = (SELECT MANAGER_ID
                     FROM EMPLOYEES
                     WHERE FIRST_NAME = 'Neena');

SELECT MANAGER_ID
FROM EMPLOYEES
WHERE FIRST_NAME = 'Neena';

SELECT W.EMPLOYEE_ID, W.FIRST_NAME, W.LAST_NAME,W.MANAGER_ID,M.EMPLOYEE_ID,M.FIRST_NAME,M.LAST_NAME
FROM EMPLOYEES W
         LEFT JOIN EMPLOYEES M
              ON W.MANAGER_ID = M.EMPLOYEE_ID
ORDER BY 1;